
<p>Vidyalaya is proud to announce opening of 2012-13 session on Sunday, 9 September 2012 at <a href="http://www.pthsd.k12.nj.us/sch/bms/bmsHome.htm">Brooklawn Middle School</a>, 250 Beachwood Drive, Parsippany, NJ 07054. Please come early to familiarize yourself with the new facility and parking and be seated by 9 AM in the cafeteria (see attached map). Please drive slowly in school premises and park only where legally permitted.</p>

   <p>We plan to email more details, including class assignment and room numbers before the opening day. We will also provide a half inch folder, pencils, eraser, sharpener, ruler and blank papers to all students this year. If you were enrolled in previous year, please bring your school bag and prayer book. All new students will be provided with a bag, a prayer book and a prayer cd.</p>

<p>We confirm that we have received tuition in the amount of $==AMOUNT== from you for 2012-13. Vidyalaya Inc. (EIN number is 26-1075463) is a tax-exempt under section 501(c)(3) of the Internal Revenue Code. Any additional donation made to Vidyalaya is tax-deductible. If your company supports non-profit organizatios, we would be love to work with you to qualify Vidyalaya for such grants.</p>

   <p>Vidyalaya has two portals to share information. The main website is <a href="http://www.vidyalaya.us">www.vidyalaya.us</a> and is primary source of information about school. Registered families also have access to the password protected content on the website. To login, please click on Login button on the top right. The login name is "member" and password is "20ritadrive" (without the quotes).</p>
<p> We also have a portal for you to view your personal information stored in our database at <a href="http://www.vidyalaya.us/dakhila">www.vidyalaya.us/dakhila</a>. To obtain/reset the password for this portal, please follow instructions at <a href="http://www.vidyalaya.us/shiksha/dakhila.html">here</a>. You can also see current class assignment on this portal. We request you to login to both the portals and let us know if you face any difficulties.</p>

<p>We look forward to another great year at Vidyalaya 2012-13.</p>

<p>--<br />Vidyalaya Admissions<br />(sent by: Umesh Mittal)</p>


