<html>
<head>
<style type="text/css">

.textfield
{
border: none;
}

table
{
border-collapse:collapse;
}

</style>
</head>
<body>

<form method="POST" action="http://www.vidyalaya.us/dakhila/php/userdata.php?command=formhelp">
<font face="calibri">

<h1>
New Family Registration
</h1>

<br />
<br />

<table border="1" >

<tr>
<td>Home Phone</td>
<td><input class="textfield" type="text" name="Home Phone" /></td>
</tr>

<tr>
<td>Address Line 1</td>
<td><input class="textfield" type="text" name="Address 1" /></td>
</tr>

<tr>
<td>Address Line 2</td>
<td><input class="textfield" type="text" name="Address 2" /></td>
</tr>

<tr>
<td>City</td>
<td><input class="textfield" type="text" name="City" /></td>
</tr>

<tr>
<td>State</td>
<td><input class="textfield" type="text" name="State" /></td>
</tr>

<tr>
<td>Zipcode</td>
<td><input class="textfield" type="text" name="Zipcode" /></td>
</tr>

</table>
<br />
<br />
<br />
<table border="1" >

<tr>
<td></td>
<td><center>Mother</center></td>
<td><center>Father</center></td>
</tr>

<tr>
<td>First Name</td>
<td><input class="textfield" type="text" name="First Name Mother" /></td>
<td><input class="textfield" type="text" name="First Name Father" /></td>
</tr>

<tr>
<td>Last Name</td>
<td><input class="textfield" type="text" name="Last Name Mother" /></td>
<td><input class="textfield" type="text" name="Last Name Father" /></td>
</tr>

<tr>
<td>Email</td>
<td><input class="textfield" type="text" name="Email Mother" /></td>
<td><input class="textfield" type="text" name="Email Father" /></td>
</tr>

<tr>
<td>Work Phone</td>
<td><input class="textfield" type="text" name="Work Phone Mother" /></td>
<td><input class="textfield" type="text" name="Work Phone Father" /></td>
</tr>

<tr>
<td>Cell Phone</td>
<td><input class="textfield" type="text" name="Cell Phone Mother" /></td>
<td><input class="textfield" type="text" name="Cell Phone Father" /></td>
</tr>

</table>
<br />
<br />
<br />
<table border="1" >

<tr>
<td></td>
<td><center>Child 1</center></td>
<td><center>Child 2</center></td>
<td><center>Child 3</center></td>
<td><center>Child 4</center></td>
</tr>

<tr>
<td>First Name</td>
<td><input class="textfield" type="text" name="First Name Child 1" /></td>
<td><input class="textfield" type="text" name="First Name Child 2" /></td>
<td><input class="textfield" type="text" name="First Name Child 3" /></td>
<td><input class="textfield" type="text" name="First Name Child 4" /></td>
</tr>

<tr>
<td>Last Name</td>
<td><input class="textfield" type="text" name="Last Name Child 1" /></td>
<td><input class="textfield" type="text" name="Last Name Child 2" /></td>
<td><input class="textfield" type="text" name="Last Name Child 3" /></td>
<td><input class="textfield" type="text" name="Last Name Child 4" /></td>
</tr>

<tr>
<td>Email</td>
<td><input class="textfield" type="text" name="Email Child 1" /></td>
<td><input class="textfield" type="text" name="Email Child 2" /></td>
<td><input class="textfield" type="text" name="Email Child 3" /></td>
<td><input class="textfield" type="text" name="Email Child 4" /></td>
</tr>

<tr>
<td>Cell Phone</td>
<td><input class="textfield" type="text" name="Cell Phone Child 1" /></td>
<td><input class="textfield" type="text" name="Cell Phone Child 2" /></td>
<td><input class="textfield" type="text" name="Cell Phone Child 3" /></td>
<td><input class="textfield" type="text" name="Cell Phone Child 4" /></td>
</tr>

<tr>
<td>Gender</td>
<td><input class="textfield" type="text" name="Gender Child 1" /></td>
<td><input class="textfield" type="text" name="Gender Child 2" /></td>
<td><input class="textfield" type="text" name="Gender Child 3" /></td>
<td><input class="textfield" type="text" name="Gender Child 4" /></td>
</tr>

<tr>
<td>Date of Birth</td>
<td><input class="textfield" type="text" name="Date of Birth Child 1" /></td>
<td><input class="textfield" type="text" name="Date of Birth Child 2" /></td>
<td><input class="textfield" type="text" name="Date of Birth Child 3" /></td>
<td><input class="textfield" type="text" name="Date of Birth Child 4" /></td>
</tr>

<tr>
<td>Language*</td>
<td><input class="textfield" type="text" name="Language Child 1" /></td>
<td><input class="textfield" type="text" name="Language Child 2" /></td>
<td><input class="textfield" type="text" name="Language Child 3" /></td>
<td><input class="textfield" type="text" name="Language Child 4" /></td>
</tr>

<tr>
<td>Grade (Fall 12)</td>
<td><input class="textfield" type="text" name="Grade Child 1" /></td>
<td><input class="textfield" type="text" name="Grade Child 2" /></td>
<td><input class="textfield" type="text" name="Grade Child 3" /></td>
<td><input class="textfield" type="text" name="Grade Child 4" /></td>
</tr>

</table>

<p>
*Please select one: Hindi, Gujurati, or Telegu.
</p>

<center>
<input type="submit" value="Submit" />
</center>

</font>
</form>

</body>
</html>